#app
server:
    port: 8080

#spring
spring:
#  devtools:
#    restart:
#      enabled: false
      
  # mvc
#  mvc:
#    view:
#      prefix: 
#      suffix:  
      
  # session
  session:
    store-type: redis
    
  # redis 
  redis:
    database: 0
    host: 127.0.0.1
    password: 
    timeout: 0
    
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 20
      min-idle: 0
      

  # DATABASE CONFIG
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sparrow?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 

#mybatis
mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*Mapper.xml
  type-aliases-package: flying.entity.sparrow
  
#mybatis-plus:
#  mapper-locations: classpath:/mybatis/mapper/**/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: flying.entity.sparrow
#  #typeEnumsPackage: com.baomidou.springboot.entity.enums
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    logic-delete-value: -1
#    logic-not-delete-value: 1
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
